"""add items created_at and updated_at

Revision ID: 2c2c98694d97
Revises: 81d9aaa3abff
Create Date: 2026-07-27 11:13:43.258718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]

revision: str = "2c2c98694d97"
down_revision: str | None = "81d9aaa3abff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "items",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "updated_at")
    op.drop_column("items", "created_at")
    # ### end Alembic commands ###
