#!/usr/bin/env bash
#
# 開発環境の初期設定チェックスクリプト
#
# docs/development-environment.md §3 と README.md「本格セットアップ」に列挙された
# 初回セットアップ項目（コンテナ同梱ツール / make setup / 各サービスへのログイン）に加え、
# docs/infrastructure.md・docs/sandbox.md が求めるリポジトリ側の GitHub Rulesets
# （main-ci-required / sandbox-isolation 等）が完了しているかを一括確認する。
# CI では使わない — ローカル/devcontainer 専用。
#
# AIコーディングエージェントCLIはClaude Code（claude）/ GitHub Copilot CLI（copilot）の
# どちらか一方が実装されていれば良い（#117: 併用/切り替えの採否は未確定）。現状
# docs/development-environment.md / README.md は Claude Code のみを前提に書かれている。
#
# Usage: ./tools/script/check-devenv-setup.sh
#
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

PASS=0
FAIL=0

section() { echo; echo "## $1"; }
ok()   { echo "  [OK] $1"; PASS=$((PASS + 1)); }
ng()   { echo "  [NG] $1"; [[ -n "${2:-}" ]] && echo "       -> $2"; FAIL=$((FAIL + 1)); }
info() { echo "  [--] $1"; }

# ---- 1. コンテナ同梱ツール ----
section "コンテナ同梱ツール"
for cmd in terraform tflint trivy checkov aws node python3 uv rg gh docker; do
  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$cmd ($(command -v "$cmd"))"
  else
    ng "$cmd が見つからない" "Dev Containers: Rebuild Container を実行"
  fi
done

# AIコーディングエージェントCLI: Claude Code（claude）/ GitHub Copilot CLI（copilot）の
# どちらか一方が使えれば良い（#117: 併用/切り替えの採否は未確定のため両対応にする。現状
# docs/development-environment.md は Claude Code のみを前提に書かれている点に注意）。
# `copilot` は VS Code の GitHub Copilot Chat 拡張が globalStorage 配下に同名の起動シムを
# 置くことがあり、`command -v` だけでは実体（npm の `@github/copilot`）と区別できない —
# 実際に `--version` を試し、未インストール時の応答文言が返ってこないかで判定する。
has_claude=false
command -v claude >/dev/null 2>&1 && has_claude=true

has_copilot=false
if command -v copilot >/dev/null 2>&1; then
  copilot_probe="$(timeout 5 copilot --version </dev/null 2>&1 || true)"
  if ! grep -qi "cannot find github copilot cli" <<<"$copilot_probe"; then
    has_copilot=true
  fi
fi

if $has_claude || $has_copilot; then
  detected=()
  $has_claude && detected+=("Claude Code ($(command -v claude))")
  $has_copilot && detected+=("GitHub Copilot CLI ($(command -v copilot))")
  # `IFS=', '`（2文字）で ${detected[*]} を展開しても joinに使われるのは先頭の1文字のみ
  # （bashの既知の挙動）なので、区切り文字は printf で明示的に組み立てる。
  detected_str="$(printf '%s, ' "${detected[@]}")"
  ok "AIコーディングエージェントCLI: ${detected_str%, }"
else
  ng "Claude Code（claude）/ GitHub Copilot CLI（copilot）のいずれも見つからない" \
    "Dev Containers: Rebuild Container を実行、または docs/development-environment.md を参照"
fi

# ---- 2. 依存関係 / pre-commit hooks（make setup）----
section "依存関係・pre-commit hooks（make setup）"
if [[ -d services/backend/python/.venv ]]; then
  ok "backend: .venv が存在する（uv sync 済み）"
else
  ng "backend: .venv が無い" "make setup（または cd services/backend/python && uv sync）"
fi

if [[ -d services/frontend/node_modules ]]; then
  ok "frontend: node_modules が存在する（npm install 済み）"
else
  ng "frontend: node_modules が無い" "make setup（または cd services/frontend && npm install）"
fi

if [[ -f .git/hooks/pre-commit ]] && grep -q "File generated by pre-commit" .git/hooks/pre-commit 2>/dev/null; then
  ok "pre-commit フックがインストール済み"
else
  ng "pre-commit フックが未インストール" "make hooks"
fi

# ---- 3. Git 設定 ----
section "Git 設定"
git_user_name="$(git config --get user.name || true)"
git_user_email="$(git config --get user.email || true)"
if [[ -n "$git_user_name" && -n "$git_user_email" ]]; then
  ok "user.name / user.email 設定済み ($git_user_name <$git_user_email>)"
else
  ng "user.name / user.email が未設定" "git config --local user.name / user.email を設定（README『Git 初期設定』参照）"
fi

origin_url=""
if git remote get-url origin >/dev/null 2>&1; then
  origin_url="$(git remote get-url origin)"
  ok "remote origin 設定済み ($origin_url)"
else
  ng "remote origin が未設定" "git remote add origin <url>"
fi

# origin のプロトコルによって push 認証手段が異なる:
#   https:// → gh の git credential helper（GitHub CLI セクションで確認済みなら OK）
#   git@ / ssh:// → SSH 公開鍵認証
if [[ "$origin_url" == https://* ]]; then
  info "origin は HTTPS — push 認証は gh の credential helper に委譲（下記『GitHub CLI』参照）"
elif [[ -n "$origin_url" ]]; then
  # ssh -T git@github.com は認証成功時も exit 1 を返す（GitHub 側の仕様: シェル
  # アクセス非対応のため）。pipefail 下でパイプに直結すると誤って NG 判定になるので、
  # 出力を変数に受けてからメッセージで判定する（ssh 自体の exit code は見ない）。
  ssh_out="$(ssh -T git@github.com -o BatchMode=yes -o ConnectTimeout=5 2>&1)"
  if grep -qi "successfully authenticated" <<<"$ssh_out"; then
    ok "SSH 認証（git@github.com）OK"
  else
    ng "SSH 認証に失敗" "GitHub に SSH 公開鍵を登録する（README『Git 初期設定』参照）"
  fi
fi

# ---- 4. GitHub CLI ----
section "GitHub CLI"
if gh auth status >/dev/null 2>&1; then
  gh_user="$(gh api user -q .login 2>/dev/null || echo 'ログイン済み')"
  ok "gh auth status OK ($gh_user)"
else
  ng "GitHub CLI 未ログイン" "gh auth login"
fi

# ---- 5. AIコーディングエージェント（ログイン状態）----
section "AIコーディングエージェント（ログイン状態）"
if $has_claude; then
  claude_config_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
  if [[ -s "$claude_config_dir/.credentials.json" ]]; then
    ok "Claude Code: 認証情報あり ($claude_config_dir/.credentials.json)"
  else
    ng "Claude Code: 未ログイン" "claude を起動してブラウザ認証を完了する"
  fi
fi
if $has_copilot; then
  # 認証解決順（GitHub公式ドキュメント）: COPILOT_GITHUB_TOKEN → GH_TOKEN → GITHUB_TOKEN →
  # システムキーチェーン（無ければ ~/.copilot/config.json への平文フォールバック）→
  # 最後に `gh auth token` へフォールバック。最後の gh 経由は「4. GitHub CLI」で確認済みなので、
  # ここでは環境変数・設定ファイルを先に見て、無ければ gh の結果を流用する。
  if [[ -n "${COPILOT_GITHUB_TOKEN:-}${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]; then
    ok "GitHub Copilot CLI: 環境変数によるトークン認証あり"
  elif [[ -s "$HOME/.copilot/config.json" ]]; then
    ok "GitHub Copilot CLI: 認証情報あり (~/.copilot/config.json)"
  elif gh auth status >/dev/null 2>&1; then
    ok "GitHub Copilot CLI: 専用の認証情報は無いが、gh 経由のフォールバック認証が有効（gh auth token）"
  else
    ng "GitHub Copilot CLI: 未ログイン" "copilot を起動して /login を実行するか、先に gh auth login を済ませる"
  fi
fi

# ---- 6. AWS SSO ----
section "AWS SSO"
if aws sts get-caller-identity >/dev/null 2>&1; then
  identity="$(aws sts get-caller-identity --query 'Account' --output text 2>/dev/null || echo '?')"
  ok "aws sts get-caller-identity OK (account: $identity)"
else
  ng "AWS 認証に失敗（未設定 or トークン期限切れ）" "./tools/script/aws-sso-setup.sh -a <account_id> -u <start_url>（期限切れのみなら aws sso login）"
fi

# ---- 7. 自分の AWS へのデプロイ用リポジトリ変数（本格セットアップ・任意）----
section "リポジトリ変数（本格セットアップ・任意 — fork して自分の AWS にデプロイする場合のみ必要）"
if gh auth status >/dev/null 2>&1; then
  vars="$(gh variable list 2>/dev/null | awk '{print $1}')"
  for v in AWS_TF_STATE_BUCKET AWS_PLAN_ROLE_ARN AWS_DEPLOY_ROLE_ARN; do
    if grep -qx "$v" <<<"$vars"; then
      ok "$v 登録済み"
    else
      info "$v 未登録（infra/bootstrap を apply していない/自分の AWS にデプロイしない場合は不要）"
    fi
  done
else
  info "gh 未ログインのためスキップ"
fi

# ---- 8. GitHub Rulesets（ブランチ保護）----
# main-ci-required / sandbox-isolation は docs/infrastructure.md「ブランチ保護（GitHub
# Rulesets）」・docs/sandbox.md「GitHub ルールセット」の記載を正として検証する
# （存在するだけでなく enforcement=active・target=branch・対象ブランチ・必須チェックまで見る）。
section "GitHub Rulesets（ブランチ保護）"

# check_ruleset <name> <期待する対象ブランチ (ref_name include)> <期待する必須チェック(空白区切り)> <doc参照先> <ok時の説明>
check_ruleset() {
  local name="$1" expected_ref="$2" expected_contexts="$3" doc_hint="$4" label="$5"

  if ! grep -qx "$name" <<<"$ruleset_names"; then
    ng "$name ルールセットが無い" "$doc_hint を参照して作成"
    return
  fi

  local rs_id enforcement target ref_includes contexts problems=""
  rs_id="$(gh api "repos/$repo_slug/rulesets" --jq ".[] | select(.name==\"$name\") | .id" 2>/dev/null)"
  enforcement="$(gh api "repos/$repo_slug/rulesets/$rs_id" --jq '.enforcement' 2>/dev/null)"
  target="$(gh api "repos/$repo_slug/rulesets/$rs_id" --jq '.target' 2>/dev/null)"
  ref_includes="$(gh api "repos/$repo_slug/rulesets/$rs_id" --jq '.conditions.ref_name.include[]' 2>/dev/null)"
  contexts="$(gh api "repos/$repo_slug/rulesets/$rs_id" \
    --jq '.rules[] | select(.type=="required_status_checks") | .parameters.required_status_checks[].context' 2>/dev/null)"

  [[ "$enforcement" == "active" ]] || problems="$problems enforcement=${enforcement:-取得失敗}（要 active）"
  [[ "$target" == "branch" ]] || problems="$problems target=${target:-取得失敗}（要 branch）"
  grep -qx "$expected_ref" <<<"$ref_includes" || problems="$problems 対象ブランチに $expected_ref が無い"

  local missing=""
  for c in $expected_contexts; do
    grep -qx "$c" <<<"$contexts" || missing="$missing $c"
  done
  [[ -z "$missing" ]] || problems="$problems 必須チェック不足:$missing"

  if [[ -z "$problems" ]]; then
    ok "$name（$label）設定済み"
  else
    ng "$name の設定に問題あり:$problems" "$doc_hint を参照して修正"
  fi
}

repo_slug="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
if [[ -z "$repo_slug" ]]; then
  info "リポジトリを特定できないためスキップ（gh repo view 失敗）"
elif ! gh api "repos/$repo_slug/rulesets" >/dev/null 2>&1; then
  info "rulesets の取得に失敗（gh 未ログイン、または admin/maintain 権限が必要）— スキップ"
else
  ruleset_names="$(gh api "repos/$repo_slug/rulesets" --jq '.[].name' 2>/dev/null)"

  check_ruleset "main-ci-required" "~DEFAULT_BRANCH" "changes backend frontend infra scripts" \
    "docs/infrastructure.md『ブランチ保護（GitHub Rulesets）』" "main の必須ステータスチェック"

  # guard は pull_request イベントでのみ起動するため、対象は ~ALL ではなく
  # ~DEFAULT_BRANCH（main へのマージ時のみ強制）が正しい設定（docs/sandbox.md 参照）。
  check_ruleset "sandbox-isolation" "~DEFAULT_BRANCH" "guard" \
    "docs/sandbox.md『GitHub ルールセット』" "sandbox-guard 必須化"
fi

# ---- サマリ ----
section "サマリ"
echo "  PASS: $PASS / FAIL: $FAIL"
if [[ $FAIL -gt 0 ]]; then
  echo
  echo "未完了の項目があります。上記 [NG] の '->' に従って対応してください。"
  exit 1
fi
echo
echo "初期設定はすべて完了しています。"
