#!/usr/bin/env bash
#
# 開発環境の初期設定チェックスクリプト
#
# docs/development-environment.md §3 と README.md「本格セットアップ」に列挙された
# 初回セットアップ項目（コンテナ同梱ツール / make setup / 各サービスへのログイン）が
# 完了しているかを一括確認する。CI では使わない — ローカル/devcontainer 専用。
#
# Usage: ./tools/script/check-devenv-setup.sh
#
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

PASS=0
FAIL=0

section() { echo; echo "## $1"; }
ok()   { echo "  [OK] $1"; PASS=$((PASS + 1)); }
ng()   { echo "  [NG] $1"; [[ -n "${2:-}" ]] && echo "       -> $2"; FAIL=$((FAIL + 1)); }
info() { echo "  [--] $1"; }

# ---- 1. コンテナ同梱ツール ----
section "コンテナ同梱ツール"
for cmd in terraform tflint trivy checkov aws node python3 uv rg gh docker claude; do
  if command -v "$cmd" >/dev/null 2>&1; then
    ok "$cmd ($(command -v "$cmd"))"
  else
    ng "$cmd が見つからない" "Dev Containers: Rebuild Container を実行"
  fi
done

# ---- 2. 依存関係 / pre-commit hooks（make setup）----
section "依存関係・pre-commit hooks（make setup）"
if [[ -d services/backend/python/.venv ]]; then
  ok "backend: .venv が存在する（uv sync 済み）"
else
  ng "backend: .venv が無い" "make setup（または cd services/backend/python && uv sync）"
fi

if [[ -d services/frontend/node_modules ]]; then
  ok "frontend: node_modules が存在する（npm install 済み）"
else
  ng "frontend: node_modules が無い" "make setup（または cd services/frontend && npm install）"
fi

if [[ -f .git/hooks/pre-commit ]] && grep -q "File generated by pre-commit" .git/hooks/pre-commit 2>/dev/null; then
  ok "pre-commit フックがインストール済み"
else
  ng "pre-commit フックが未インストール" "make hooks"
fi

# ---- 3. Git 設定 ----
section "Git 設定"
git_user_name="$(git config --get user.name || true)"
git_user_email="$(git config --get user.email || true)"
if [[ -n "$git_user_name" && -n "$git_user_email" ]]; then
  ok "user.name / user.email 設定済み ($git_user_name <$git_user_email>)"
else
  ng "user.name / user.email が未設定" "git config --local user.name / user.email を設定（README『Git 初期設定』参照）"
fi

origin_url=""
if git remote get-url origin >/dev/null 2>&1; then
  origin_url="$(git remote get-url origin)"
  ok "remote origin 設定済み ($origin_url)"
else
  ng "remote origin が未設定" "git remote add origin <url>"
fi

# origin のプロトコルによって push 認証手段が異なる:
#   https:// → gh の git credential helper（GitHub CLI セクションで確認済みなら OK）
#   git@ / ssh:// → SSH 公開鍵認証
if [[ "$origin_url" == https://* ]]; then
  info "origin は HTTPS — push 認証は gh の credential helper に委譲（下記『GitHub CLI』参照）"
elif [[ -n "$origin_url" ]]; then
  # ssh -T git@github.com は認証成功時も exit 1 を返す（GitHub 側の仕様: シェル
  # アクセス非対応のため）。pipefail 下でパイプに直結すると誤って NG 判定になるので、
  # 出力を変数に受けてからメッセージで判定する（ssh 自体の exit code は見ない）。
  ssh_out="$(ssh -T git@github.com -o BatchMode=yes -o ConnectTimeout=5 2>&1)"
  if grep -qi "successfully authenticated" <<<"$ssh_out"; then
    ok "SSH 認証（git@github.com）OK"
  else
    ng "SSH 認証に失敗" "GitHub に SSH 公開鍵を登録する（README『Git 初期設定』参照）"
  fi
fi

# ---- 4. GitHub CLI ----
section "GitHub CLI"
if gh auth status >/dev/null 2>&1; then
  gh_user="$(gh api user -q .login 2>/dev/null || echo 'ログイン済み')"
  ok "gh auth status OK ($gh_user)"
else
  ng "GitHub CLI 未ログイン" "gh auth login"
fi

# ---- 5. Claude Code ----
section "Claude Code"
claude_config_dir="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
if [[ -s "$claude_config_dir/.credentials.json" ]]; then
  ok "認証情報あり ($claude_config_dir/.credentials.json)"
else
  ng "Claude Code 未ログイン" "claude を起動してブラウザ認証を完了する"
fi

# ---- 6. AWS SSO ----
section "AWS SSO"
if aws sts get-caller-identity >/dev/null 2>&1; then
  identity="$(aws sts get-caller-identity --query 'Account' --output text 2>/dev/null || echo '?')"
  ok "aws sts get-caller-identity OK (account: $identity)"
else
  ng "AWS 認証に失敗（未設定 or トークン期限切れ）" "./tools/script/aws-sso-setup.sh -a <account_id> -u <start_url>（期限切れのみなら aws sso login）"
fi

# ---- 7. 自分の AWS へのデプロイ用リポジトリ変数（本格セットアップ・任意）----
section "リポジトリ変数（本格セットアップ・任意 — fork して自分の AWS にデプロイする場合のみ必要）"
if gh auth status >/dev/null 2>&1; then
  vars="$(gh variable list 2>/dev/null | awk '{print $1}')"
  for v in AWS_TF_STATE_BUCKET AWS_PLAN_ROLE_ARN AWS_DEPLOY_ROLE_ARN; do
    if grep -qx "$v" <<<"$vars"; then
      ok "$v 登録済み"
    else
      info "$v 未登録（infra/bootstrap を apply していない/自分の AWS にデプロイしない場合は不要）"
    fi
  done
else
  info "gh 未ログインのためスキップ"
fi

# ---- サマリ ----
section "サマリ"
echo "  PASS: $PASS / FAIL: $FAIL"
if [[ $FAIL -gt 0 ]]; then
  echo
  echo "未完了の項目があります。上記 [NG] の '->' に従って対応してください。"
  exit 1
fi
echo
echo "初期設定はすべて完了しています。"
