# Web (SPA) hosting: private S3 origin behind CloudFront.

# Private bucket that holds the built SPA (`dist/`). Never public; CloudFront
# reaches it via an Origin Access Control (see TODO below).
resource "aws_s3_bucket" "web" {
  # Globally unique namespace across all AWS accounts -- see
  # local.global_name_prefix (main.tf) for why this isn't name_prefix alone.
  bucket = "${local.global_name_prefix}-web"

  # This bucket only ever holds the built SPA (regenerated by cd-app*.yml's
  # `npm run build` + `aws s3 sync`), never primary data, so allowing
  # `terraform destroy` to delete a non-empty bucket is safe. Without this,
  # golden-path-verify's teardown fails with BucketNotEmpty after every run
  # that actually deployed.
  force_destroy = true
}

resource "aws_s3_bucket_public_access_block" "web" {
  bucket = aws_s3_bucket.web.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "web" {
  bucket = aws_s3_bucket.web.id

  versioning_configuration {
    status = "Enabled"
  }
}

# SSE-S3 (AES256), not SSE-KMS: CloudFront's Origin Access Control (OAC) can only
# decrypt SSE-KMS objects encrypted with a customer-managed key (CMK), never the
# AWS-managed key (alias/aws/s3) -- #587's SSE-KMS attempt used the latter, so
# every CloudFront request to this origin got a 403 AccessDenied from S3 and the
# SPA never loaded at all (#591). #280 already declined introducing a CMK, so
# SSE-S3 is what's left. This leaves checkov's CKV_AWS_145 (S3 should use KMS) as
# a known, already-accepted soft-fail finding (see the `security` target comment
# in Makefile, #111) rather than a bug to fix again.
resource "aws_s3_bucket_server_side_encryption_configuration" "web" {
  bucket = aws_s3_bucket.web.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Versioned SPA builds otherwise keep every noncurrent version forever (#303).
# Built assets are reproducible from source, so a short retention is fine.
resource "aws_s3_bucket_lifecycle_configuration" "web" {
  bucket = aws_s3_bucket.web.id

  rule {
    id     = "expire-noncurrent-web-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 30
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.web]
}

# CloudFront in front of the SPA (S3 via OAC) with an `/api/*` behavior to the ALB.

resource "aws_cloudfront_origin_access_control" "web" {
  name                              = "${local.name_prefix}-web-oac"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# SPA client-side routing fallback, scoped to the S3 origin only (#439).
#
# Previously this was a distribution-wide `custom_error_response` (403/404 ->
# 200 + /index.html), which also applied to the /api/* behavior since
# custom_error_response has no per-behavior/per-origin scoping in CloudFront.
# That masked genuine API error responses (e.g. a 403 for missing OAuth
# scope) as "200 + SPA HTML", making them unobservable from the browser and
# from live-smoke (#376) -- see devcon-test#19/#20 for how this delayed
# diagnosing a real authz regression.
#
# This function is attached only to default_cache_behavior (the S3 origin,
# below), so it never runs for /api/* requests -- CloudFront selects the
# cache behavior (and thus which functions apply) from the original request
# path before invoking any viewer-request function. Rewriting the request URI
# here also fully avoids the S3-side 403 that OAC-protected buckets return
# for a missing key (no s3:ListBucket permission to tell 403 from 404 apart),
# so no custom_error_response is needed for the S3 origin either.
resource "aws_cloudfront_function" "spa_routing" {
  name    = "${local.name_prefix}-spa-routing"
  runtime = "cloudfront-js-2.0"
  comment = "Rewrite extension-less SPA routes to /index.html before hitting the S3 origin"
  publish = true

  # Extension-less request paths (client-side routes like /orders/1) are
  # rewritten to /index.html so the SPA can handle routing. Paths with a
  # file extension (assets: .js/.css/.png/...) pass through unchanged --
  # a genuinely missing asset now surfaces its real S3/OAC error status
  # instead of being masked as 200.
  code = <<-EOT
    function handler(event) {
      var request = event.request;
      var uri = request.uri;

      if (!uri.includes(".")) {
        request.uri = "/index.html";
      }

      return request;
    }
  EOT
}

# AWS-managed cache / origin-request policies (well-known IDs).
locals {
  cf_cache_optimized      = "658327ea-f89d-4fab-a63d-7e88639e58f6" # CachingOptimized
  cf_cache_disabled       = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # CachingDisabled
  cf_orp_all_viewer_nohdr = "b689b0a8-53d0-40ab-baf2-68738e2966ac" # AllViewerExceptHostHeader
}

# Security headers for the SPA (HTML/JS/CSS) responses from the S3 origin. Not attached to
# the /api/* behavior: that origin returns JSON, not browser-rendered HTML, and gets its own
# headers if/when the API adds them. The CSP has no 'unsafe-inline'/nonce because the Vite
# production build (`dist/index.html`) has no inline <script>/<style> — verified against the
# actual build output. If a future dependency injects inline styles/scripts, this policy will
# need a nonce or hash added alongside it, not just a blanket 'unsafe-inline'.
resource "aws_cloudfront_response_headers_policy" "web_security_headers" {
  name = "${local.name_prefix}-web-security-headers"

  security_headers_config {
    content_security_policy {
      override = true
      content_security_policy = join("; ", [
        "default-src 'self'",
        "script-src 'self'",
        "style-src 'self'",
        "img-src 'self' data:",
        "font-src 'self'",
        # 'self' alone breaks Cognito Hosted UI login (#365): oidc-client-ts
        # fetches the OIDC discovery document from the Cognito issuer and
        # POSTs to the Hosted UI domain's token endpoint during
        # signinRedirectCallback, both cross-origin from this CloudFront
        # domain. Neither was exercised by any pre-#365 test (local dev
        # goes through Vite's proxy, and this response-headers policy only
        # applies to the deployed CloudFront distribution), so the gap went
        # undetected until a real-browser sandbox E2E run caught it.
        "connect-src 'self' https://cognito-idp.${var.aws_region}.amazonaws.com https://${aws_cognito_user_pool_domain.hosted_ui.domain}.auth.${var.aws_region}.amazoncognito.com",
        "object-src 'none'",
        "base-uri 'none'",
        "frame-ancestors 'none'",
        "form-action 'self'",
        "upgrade-insecure-requests",
      ])
    }

    content_type_options {
      override = true
    }

    frame_options {
      override     = true
      frame_option = "DENY"
    }

    referrer_policy {
      override        = true
      referrer_policy = "strict-origin-when-cross-origin"
    }

    strict_transport_security {
      override                   = true
      access_control_max_age_sec = 63072000 # 2 years
      include_subdomains         = true
      preload                    = true
    }
  }
}

resource "aws_cloudfront_distribution" "web" {
  enabled             = true
  default_root_object = "index.html"
  comment             = "${local.name_prefix} SPA + /api"

  origin {
    origin_id                = "s3-web"
    domain_name              = aws_s3_bucket.web.bucket_regional_domain_name
    origin_access_control_id = aws_cloudfront_origin_access_control.web.id
  }

  origin {
    origin_id   = "alb-api"
    domain_name = aws_lb.api.dns_name

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "http-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }

    # Proves to the ALB (see aws_lb_listener_rule.api_from_cloudfront, api.tf) that a
    # request actually came through this distribution, not a third party's CloudFront
    # pointed at the same public ALB DNS name (#153, #271).
    custom_header {
      name  = "X-Origin-Verify"
      value = random_password.cf_origin_verify.result
    }
  }

  default_cache_behavior {
    target_origin_id           = "s3-web"
    viewer_protocol_policy     = "redirect-to-https"
    allowed_methods            = ["GET", "HEAD", "OPTIONS"]
    cached_methods             = ["GET", "HEAD"]
    cache_policy_id            = local.cf_cache_optimized
    response_headers_policy_id = aws_cloudfront_response_headers_policy.web_security_headers.id

    function_association {
      event_type   = "viewer-request"
      function_arn = aws_cloudfront_function.spa_routing.arn
    }
  }

  ordered_cache_behavior {
    path_pattern             = "/api/*"
    target_origin_id         = "alb-api"
    viewer_protocol_policy   = "redirect-to-https"
    allowed_methods          = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods           = ["GET", "HEAD"]
    cache_policy_id          = local.cf_cache_disabled
    origin_request_policy_id = local.cf_orp_all_viewer_nohdr
  }

  # No distribution-wide custom_error_response here (#439): it would also
  # mask /api/* error responses. SPA routing fallback is handled by
  # aws_cloudfront_function.spa_routing on default_cache_behavior instead.

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  price_class = "PriceClass_200"
}

# Bucket policy: only this CloudFront distribution may read objects (via OAC).
data "aws_iam_policy_document" "web_oac" {
  statement {
    sid       = "AllowCloudFrontOAC"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.web.arn}/*"]

    principals {
      type        = "Service"
      identifiers = ["cloudfront.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceArn"
      values   = [aws_cloudfront_distribution.web.arn]
    }
  }
}

resource "aws_s3_bucket_policy" "web" {
  bucket = aws_s3_bucket.web.id
  policy = data.aws_iam_policy_document.web_oac.json
}

# TODO (optional, when var.domain_name != ""): ACM cert in us-east-1 + Route53
# alias record for the custom domain.
