// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendItemNote = `-- name: AppendItemNote :one
UPDATE items
SET description = concat_ws(' | ', description, $1::text)
WHERE id = $2
RETURNING id, name, description
`

type AppendItemNoteParams struct {
	Note string `json:"note"`
	ID   int32  `json:"id"`
}

type AppendItemNoteRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) AppendItemNote(ctx context.Context, arg AppendItemNoteParams) (AppendItemNoteRow, error) {
	row := q.db.QueryRow(ctx, appendItemNote, arg.Note, arg.ID)
	var i AppendItemNoteRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getItem = `-- name: GetItem :one

SELECT id, name, description FROM items WHERE id = $1
`

type GetItemRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// Queries against the `items` table (owned by services/backend/python's Alembic — see
// internal/db/schema.sql). Backs the worker's item-note-append job (cmd/worker, #639).
func (q *Queries) GetItem(ctx context.Context, id int32) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i GetItemRow
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
