// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AppendItemNote(ctx context.Context, arg AppendItemNoteParams) (Item, error)
	// Queries against the `items` table (owned by services/backend/python's Alembic — see
	// internal/db/schema.sql). Backs the worker's item-note-append job (cmd/worker, #639).
	GetItem(ctx context.Context, id int32) (Item, error)
}

var _ Querier = (*Queries)(nil)
